### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/DPG-OS-CM-Open-Terms-Archive#20]
### Problem Statement
1. Clicking on the plus sign on the homepage led me to a dead end
<img width="1512" alt="Screen Shot 2023-07-12 at 09 14 44" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/865ea6fd-8a70-4e56-9e9b-fbadbf1bb116">
2. Clicking on declarations led me to a 404
<img width="821" alt="Screen Shot 2023-07-12 at 08 48 56" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/5e18da0f-16d3-4ee1-8822-ee22fd8ce695">

### Resources
<img width="1512" alt="Screen Shot 2023-07-12 at 08 36 08" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/73b48861-3ebe-4bf9-a797-bd16535b351d">
<img width="1512" alt="Screen Shot 2023-07-12 at 08 47 10" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/c45302f6-c717-47fb-9d45-04b8628b5bdd">

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [ ] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
Insert the right link there

**Comment by MattiSG** [comment]
The links were fixed a few months ago 🙂
