### ISSUE TITLE
Create new labels for proper prioritization and visibility

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/DPG-OS-CM-Open-Terms-Archive#5]
### Problem Statement
Most of the issues on the issues page are either not properly labelled or not labelled at all.

### Additional Information
<img width="1355" alt="Screen Shot 2023-06-29 at 09 18 41" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/3eb4c256-12fa-40a1-b90a-e06e1e7b5d87">

### What happens if this is not addressed
Let's say someone decides to make some contributions today, without proper labelling, it's difficult for the person to know which of the issues are high or low priority, their complexities, and whether or not they're beginner friendly.

### Resources
[Here's a helpful guide to labelling on Github](https://seantrane.com/posts/logical-colorful-github-labels-18230/#:~:text=Issue%2FPR%20labels%20should%20only,intuitive%20at%2Da%2Dglance.)

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [ ] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team

### Potential solutions [draft]
- Create new labels on the GitHub repositories
- Thoroughly go through all pending issues and label them effectively

**Comment by MattiSG** [comment]
The engine automatically adds labels on versions repositories since [v0.32](https://github.com/OpenTermsArchive/engine/releases/tag/v0.32.0). For the engine itself, the level of onboarding necessary for meaningful contribution rules out any systematic labelling of issues.
