### ISSUE TITLE
Linking documentation for the collection repo in the readme

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/DPG-OS-CM-Open-Terms-Archive#7]
### Problem Statement
We need to add a link to the documentation in the readme for the database repos so as to make it easier and more accessible to anyone visiting the repos

### Additional Information
_GIF of the current status_
![msedge_C3ZVC1gFsn](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/edbe0554-dceb-44c6-8c19-0f71a2a94a76)

### What happens if this is not addressed
If this is not addressed, some contributors might get lost or have a hard time finding the related documentation

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
We can add the same link in the about section of the repository to the Readme file of the related GitHub repo

**Comment by Cli4d** [comment]
This issue touched on a lot of the repositories for collections. So it's quite hard to know which one repo can it be transferred to

**Comment by MattiSG** [comment]
Done as part of Hacktoberfest preparations in https://github.com/OpenTermsArchive/contrib-versions/pull/21 and mirrored onto other collections 🙂
